version: "3.9"

services:
    nginx:
        container_name: nginx_container
        image: nginx:1.21.6-alpine
        ports:
            - ${WEB_PORT}:80
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - cake
            - mysql
        networks:
            - frontend

    cake:
        container_name: cake_container
        build: ./docker/php
        ports:
            - ${CAKE_PORT}:${CAKE_PORT}
        volumes:
            - ./src:/var/www
        depends_on:
            - mysql
        networks:
            - frontend
            - backend

    mysql:
        container_name: mysql_container
        image: mysql:8.0.26
        platform: "linux/amd64"
        volumes:
            - ./docker/mysql/mysql_data:/var/lib/mysql
            - ./logs:/var/log/mysql
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
            TZ: "Asia/Tokyo"
        networks:
            - backend

    pma:
        container_name: pma_container
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=${DB_USER}
            - PMA_PASSWORD=${DB_PASS}
        ports:
            - ${PMA_PORT}:80
        volumes:
            - /sessions
        networks:
            - backend

networks:
    frontend:
        name: frontend_nw
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/24
    backend:
        name: backend_nw
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.20.0/24
